### ISSUE TITLE
Add contributors

### ISSUE THREAD

**Issue by baumannzone** [onebeyond/css-pills#1]
Please @all-contributors add @baumannzone for code

**Comment by UlisesGascon** [comment]
Done, permissions granted :)

**Comment by baumannzone** [comment]
Please @all-contributors add @baumannzone for code

**Comment by baumannzone** [comment]
Please @all-contributors add @eduvilla97 for code

**Comment by baumannzone** [comment]
Please @all-contributors add @ArshiaSaleem98 for code
